string prompt                    # prompt
string original_message          # original message
sensor_msgs/Image[] images       # image for VLMs
---
Response response                # final response
---
PartialResponse partial_response  # partial response
